# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 11:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=400)),
                ('foto', models.ImageField(default='nofoto.jpg', null=True, upload_to='static/img/fotografos')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.FileField(null=True, upload_to='static/resultados')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='resumen',
        ),
        migrations.AddField(
            model_name='carrera',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='precio',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='carrera',
            name='texto',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor.fields.RichTextField(max_length=99999999),
        ),
        migrations.AddField(
            model_name='resultados',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcarmona.Carrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubcarmona.Tipo'),
            preserve_default=False,
        ),
    ]
