# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.TextField(default=models.TextField(max_length=99999999), max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(max_length=99999999),
        ),
    ]
