# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('foto', models.ImageField(default='nofoto.jpg', null=True, upload_to='static/img/proximosEventos')),
                ('ciudad', models.CharField(max_length=200)),
                ('provicia', models.CharField(default='Cádiz', max_length=200)),
                ('distancia', models.IntegerField(max_length=100000)),
            ],
        ),
    ]
