# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0004_auto_20160719_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.TextField(blank=True, default=' ', max_length=350, null=True),
        ),
    ]
