# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0005_auto_20160719_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=400)),
                ('foto', models.ImageField(default='nofoto.jpg', null=True, upload_to='static/img/fotografos')),
            ],
        ),
    ]
