# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 11:58
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0007_remove_post_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='link',
            field=models.CharField(default=datetime.datetime(2016, 7, 25, 11, 58, 19, 988865, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='texto',
            field=models.CharField(default=datetime.datetime(2016, 7, 25, 11, 58, 43, 969481, tzinfo=utc), max_length=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor.fields.RichTextField(max_length=99999999),
        ),
    ]
