# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0008_auto_20160725_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.FileField(null=True, upload_to='static/resultados')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubcarmona.Carrera')),
            ],
        ),
    ]
