# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubcarmona', '0009_resultados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultados',
            old_name='titulo',
            new_name='carrera',
        ),
    ]
